// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKIKJQC75-b5LptBLOI45YPWlzKhGzn4',
    appId: '1:183577078519:web:bd9f1dc679562bb4f041f2',
    messagingSenderId: '183577078519',
    projectId: 'chat-app-2f58f',
    authDomain: 'chat-app-2f58f.firebaseapp.com',
    storageBucket: 'chat-app-2f58f.firebasestorage.app',
    measurementId: 'G-0JFHW8SYBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7di9Z_S4oB4MMsxRtonP8f7H55mwmblY',
    appId: '1:183577078519:android:ebe2c260ec448094f041f2',
    messagingSenderId: '183577078519',
    projectId: 'chat-app-2f58f',
    storageBucket: 'chat-app-2f58f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiIhjkfDULp95OhSWsXD_8tg0tGmcK62A',
    appId: '1:183577078519:ios:d07a6c8427082bd2f041f2',
    messagingSenderId: '183577078519',
    projectId: 'chat-app-2f58f',
    storageBucket: 'chat-app-2f58f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiIhjkfDULp95OhSWsXD_8tg0tGmcK62A',
    appId: '1:183577078519:ios:d07a6c8427082bd2f041f2',
    messagingSenderId: '183577078519',
    projectId: 'chat-app-2f58f',
    storageBucket: 'chat-app-2f58f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKIKJQC75-b5LptBLOI45YPWlzKhGzn4',
    appId: '1:183577078519:web:bf822b6ff935f7f1f041f2',
    messagingSenderId: '183577078519',
    projectId: 'chat-app-2f58f',
    authDomain: 'chat-app-2f58f.firebaseapp.com',
    storageBucket: 'chat-app-2f58f.firebasestorage.app',
    measurementId: 'G-24ETTRMDK5',
  );
}
